name: Run Selenium Script

on:
  workflow_dispatch:  # lets you run manually
  schedule:
    - cron: '0 * * * *'  # runs every hour (optional - remove if not needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt update
        sudo apt install -y chromium-chromedriver
        sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin
        sudo apt install -y chromium-browser

    - name: Run script
      env:
        DISPLAY: ":99"
      run: python main.py
